---
- name: Playbook to Install Apache Tomcat
  hosts: all
  become: true
  gather_facts: yes
  vars_files:
     - tomcat_vars.yml  

  tasks:
  - name: Install Java 11 Version
    yum:
      name: java-11
      state: installed

  - name: Downloading Tomcat Package
    get_url:
     url: "{{ tomcat_url }}"
     dest: /opt
     mode: 0755

  - name: Extract Package
    unarchive:
      src: /opt/{{tomcat_package}}.tar.gz
      dest: /opt/
      remote_src: yes  

  - name: Change permissions on apache-tomcat-file
    file:
      path: opt/{{ tomcat_package }}
      mode: 0755
      recurse: yes

  - name: Creating a Link File for Tomcat Startup.sh & Shutdown.sh
    file:
      src: /opt/{{ tomcat_package }}/bin/{{ item.tomcat_script }}
      dest: /usr/local/bin/{{ item.tomcat_cmd }}
      state: link
    loop:
      - { tomcat_script: startup.sh, tomcat_cmd: tomcatup }
      - { tomcat_script: shutdown.sh, tomcat_cmd: tomcatdown }

  - name: change port number
    lineinfile:
      path: /opt/{{ tomcat_package }}/conf/server.xml
      regexp: <Connector port="8090" protocol="HTTP/1.1"
      line: <Connector port="8080" protocol="HTTP/1.1"
      state: present   


  - name: Start the Tomcat Service
    command: nohup ./startup.sh
    args: 
      chdir: /opt/{{ tomcat_package }}/bin
      

     


