---
- name: Installing HTTPD Package
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Installing HTTPD
    yum: 
      name: httpd
      state: present
      
  - name: Httpd Service Start
    service:
      name: httpd
      state: started

