---
- name: Install Httpd in Ubuntu Server
  hosts: all
  become: true
  gather_facts: yes
  
  tasks:
  - name: install apache2
    apt:
     name: apache2
     update_cache: yes
     state: latest

  - name: Start Service
    service:
      name: apache2
      state: started

  - name: Copy files
    copy: 
     src: /home/ansadmin/playbooks/index.html
     dest: /var/www/html/

