---
- name: Playbook to Install Apache Tomcat
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: Install Java 11 Version
    yum:
      name: java-11
      state: installed

  - name: Downloading Tomcat Package
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
     dest: /opt
     mode: 0755

  - name: Extract Package
    unarchive:
      src: /opt/apache-tomcat-9.0.76.tar.gz
      dest: /opt/
      remote_src: yes  

  - name: Change permissions on apache-tomcat-file
    file:
      path: /opt/apache-tomcat-9.0.76
      mode: 0755

  - name: Creating Symbolic Link File to TomcatUp
    file:
     src: /opt/apache-tomcat-9.0.76/bin/startup.sh
     dest: /usr/local/bin/tomcatup
     state: link

  - name: Creating Symbolic Link File to TomcatDown
    file:
     src: /opt/apache-tomcat-9.0.76/bin/shutdown.sh
     dest: /usr/local/bin/tomcatdown
     state: link

  - name: Start the Tomcat Service
    command: nohup ./startup.sh
    args: 
      chdir: /opt/apache-tomcat-9.0.76/bin
      

     


