---
- name: Create User
  hosts: all
  become: true
  gather_facts: no
  vars:
    user_name: babaji

  tasks:
  - name: creating user {{user_name}}
    user:
      name: "{{user_name}}"

  - name: creating directory for {{ user_name}}
    file:
      path: /opt/{{user_name}}_temp_dir
      state: directory
      owner: "{{user_name}}"
      group: "{{user_name}}"
      mode: 0755
      


